CREATE SCHEMA IF NOT EXISTS netology;

CREATE TABLE IF NOT EXISTS netology.customers
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(50),
    surname character varying(50),
    age integer,
    phone_number character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT customers_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS netology.orders
(
    id           integer          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    date         timestamp without time zone DEFAULT now(),
    customer_id  integer
        constraint orders_customers_id_fk references netology.customers,
    product_name varchar(50)      NOT NULL,
    amount       double precision NOT NULL,
    PRIMARY KEY (id)
);
